@startuml

actor USER
activate USER
activate InputFunction
activate SWITHCHES
activate 8_Digits_Display
activate ConfirmFunction
activate ModifyFunction
activate ForgetFunction

== Normal Input Mode ==
USER -> InputFunction: Press BTN_Input
InputFunction -> SWITHCHES: Active switches
activate SWITHCHES
activate InputFunction
USER -> SWITHCHES: Input with switches
deactivate InputFunction
SWITHCHES -> 8_Digits_Display: Display input value
activate 8_Digits_Display
USER -> ConfirmFunction: When USER press BTN_Confirm
activate ConfirmFunction
ConfirmFunction -> ConfirmFunction: Check input is correct or not
ConfirmFunction -> 8_Digits_Display: Display Result

deactivate ConfirmFunction
deactivate SWITHCHES
deactivate 8_Digits_Display

== Modify Password Mode==
USER -> InputFunction: Press BTN_Input
InputFunction -> SWITHCHES: Active switches
activate SWITHCHES
activate InputFunction
USER -> SWITHCHES: Input with switches
deactivate InputFunction
SWITHCHES -> 8_Digits_Display: Display input value
activate 8_Digits_Display
USER -> ConfirmFunction: When USER press BTN_Confirm
activate ConfirmFunction
ConfirmFunction -> ConfirmFunction: Check input is correct or not
ConfirmFunction -> 8_Digits_Display: Display Result

deactivate ConfirmFunction
deactivate SWITHCHES
deactivate 8_Digits_Display
USER -> ModifyFunction: Press BTN_Modify if Result is correct
activate ModifyFunction
ModifyFunction -> SWITHCHES: Active switches
deactivate ModifyFunction
activate SWITHCHES
USER -> SWITHCHES: Input new code sequence
SWITHCHES -> 8_Digits_Display: Display user input
activate 8_Digits_Display
USER -> ConfirmFunction: Press BTN_Confirm, already input new code sequence
deactivate SWITHCHES
activate ConfirmFunction
ConfirmFunction -> ConfirmFunction: Change current password to new password
ConfirmFunction -> 8_Digits_Display: Display OK
deactivate ConfirmFunction
deactivate 8_Digits_Display

== Forget Password Mode ==

USER -> ForgetFunction: Press BTN_Forget, it temporarily change right password to security password
activate ForgetFunction
ForgetFunction -> SWITHCHES: Active switches
deactivate ForgetFunction
activate SWITHCHES
USER -> SWITHCHES: Input with switches
SWITHCHES -> 8_Digits_Display: Display input value
activate 8_Digits_Display
USER -> ConfirmFunction: When USER press BTN_Confirm
activate ConfirmFunction
ConfirmFunction -> ConfirmFunction: Check input is correct or not
ConfirmFunction -> 8_Digits_Display: Display Result

deactivate ConfirmFunction
deactivate SWITHCHES
deactivate 8_Digits_Display
USER -> ModifyFunction: Press BTN_Modify if Result is correct
activate ModifyFunction
ModifyFunction -> SWITHCHES: Active switches
deactivate ModifyFunction
activate SWITHCHES
USER -> SWITHCHES: Input new code sequence
SWITHCHES -> 8_Digits_Display: Display user input
activate 8_Digits_Display
USER -> ConfirmFunction: Press BTN_Confirm, already input new code sequence
deactivate SWITHCHES
activate ConfirmFunction
ConfirmFunction -> ConfirmFunction: Change current password to new password
ConfirmFunction -> 8_Digits_Display: Display OK
deactivate ConfirmFunction
deactivate 8_Digits_Display








@enduml